[build]
  # First install --include=dev the dependencies, then run the build command
  command = "ls -al && npm install --include=dev && npm run build && ls -al"
  
  # Directory to publish after build, usually your dist folder
  publish = "dist"
  
  # Environment variables
  [build.environment]
    NODE_ENV = "production"

[context.production]
  # Settings for production deployment
  command = "ls -al && npm install --include=dev && npm run build && ls -al"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
