[build]
  # Command to build your project using Webpack
  command = "npm run build"
  
  # Directory to publish after build, usually your dist folder
  publish = "dist"
  
  # Environment variables (if needed)
  environment = { 
    NODE_ENV = "production" 
  }

[context.production]
  # Settings for production deployment
  command = "npm run build"
  
  # Directory for production publish
  publish = "dist"
  
  # Plugins or post-processing (Optional)
  # [plugins]
  # [[plugins]]
  # package = "@netlify/plugin-lighthouse"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[plugins]]
  # Plugin to keep older versions (optional)
  package = "@netlify/plugin-keep-previous-builds"
