[build]
  # First install --include=dev the dependencies, then run the build command
  command = "npm install --include=dev && npm run build"
  
  # Directory to publish after build, usually your dist folder
  publish = "dist/v1.1"  # Update this path for each new version
  
  # Environment variables
  [build.environment]
    NODE_ENV = "production"

[context.production]
  # Settings for production deployment
  command = "npm install --include=dev && npm run build"
  publish = "dist/v1.1"  # Update this path for each new version

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
