[build]
  command = "chmod +x build-commands.sh && ./build-commands.sh"
  publish = "dist"

  # Environment variables
  [build.environment]
    NODE_ENV = "production"

[context.production]
  command = "chmod +x build-commands.sh && ./build-commands.sh"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
