[build]
  command = "chmod +x build-commands.sh && ./build-commands.sh"
  publish = "dist"


  [build.lifecycle]
    postbuild = "ls -al && ls -al dist"

  # Environment variables
  [build.environment]
    NODE_ENV = "production"

[context.production]
  command = "chmod +x build-commands.sh && ./build-commands.sh"
  publish = "dist"

  # Post-build script specifically for production
  [context.production.build.lifecycle]
    postbuild = "ls -al && ls -al dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200
