[build]
  # Command to build your project using Webpack
  command = "npm run build"
  
  # Directory to publish after build, usually your dist folder
  publish = "dist"
  
  # Environment variables
  [build.environment]
    NODE_ENV = "production"

[context.production]
  # Settings for production deployment
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[plugins]]
  # Plugin to keep older versions (optional)
  package = "@netlify/plugin-keep-previous-builds"
